version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
