# Generated by Django 4.2.3 on 2023-07-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_approvedpost_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvedpost",
            name="post",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="news.post"
            ),
        ),
    ]
