# Generated by Django 4.2.3 on 2023-07-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_approvedpost_post"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
    ]
